# Generated by Django 5.0.7 on 2025-03-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0003_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proApp.collector'),
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proApp.organizer'),
        ),
    ]
