# Generated by Django 5.0.7 on 2025-03-06 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0004_wastecollectionrequest_collector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proApp.organizer')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proApp.collector')),
            ],
        ),
    ]
