# Generated by Django 5.0.7 on 2025-03-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0005_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
