# Generated by Django 5.0.7 on 2025-03-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0006_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
