# Generated by Django 4.2.7 on 2025-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0007_wastecollectionrequest_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
    ]
