# Generated by Django 4.2.7 on 2025-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0008_wastecollectionrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='assign_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
