# Generated by Django 4.2.7 on 2025-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0009_wastecollectionrequest_assign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='idproof',
            field=models.ImageField(blank=True, null=True, upload_to='proof/'),
        ),
    ]
