# Generated by Django 5.2.9 on 2026-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0010_collector_idproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='collector_payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
